import { OpenApiInfoObject as InfoObject } from '@orval/core'
import fs from 'fs'
import orval from 'orval'
import path from 'path'
import { DEFAULT_SCHEMA_TITLE } from '../constants.js'
import { NoFilesGeneratedError } from '../errors.js'
import {
  formatFileWithPrettier,
  getPackageDetails,
  hasOnlyComments,
  OutputOverrider,
} from '../helper.js'
import { logger } from '../logger.js'
import { GenerateK6SDKOptions } from '../type.js'
import { getK6ClientBuilder } from './k6Client.js'

const outputOverrider = OutputOverrider.getInstance()
const packageDetails = getPackageDetails()

const generatedFileHeaderGenerator = (info: InfoObject) => {
  return [
    `Automatically generated by ${packageDetails.name}: ${packageDetails.version}`,
    `Do not edit manually.`,
    ...(info.title ? [info.title] : []),
    ...(info.description ? [info.description] : []),
    ...(info.version ? [`Service version: ${info.version}`] : []),
  ]
}

const afterAllFilesWriteHandler = async (
  filePaths: string[],
  outputOverrider: OutputOverrider
) => {
  const removeSingleFile = (filePath: string) => {
    try {
      fs.unlinkSync(filePath)
    } catch (error) {
      // This is non-critical, so we just log it
      logger.debug(
        `afterAllFilesWriteHandler ~ Error deleting file ${filePath}: ${error}`
      )
    }
  }
  const emptyFileList: string[] = []

  for (const filePath of filePaths) {
    // There is a bug in the orval library which generates empty files when tags filter is applied
    // and no matching endpoints are found and used mode is split or single.
    // It generates the file with only the header comment.
    // Hence, we manually remove those empty files.
    // Issue link - https://github.com/orval-labs/orval/issues/1691

    const fileContent = fs.readFileSync(filePath, 'utf-8')
    if (hasOnlyComments(fileContent)) {
      emptyFileList.push(filePath)
      // Delete the file
      removeSingleFile(filePath)
      continue
    }

    // Replace usages of Blob type with the k6-compatible ArrayBuffer
    const newFileContent = fileContent.replaceAll(
      /(^|\W)Blob(?!\w)/g,
      '$1ArrayBuffer'
    )

    fs.writeFileSync(filePath, newFileContent)

    try {
      await formatFileWithPrettier(filePath)
    } catch (error) {
      await outputOverrider.temporarilyWriteToStdoutAndStderr(async () => {
        logger.error(`Error in formatting file ${filePath}: ${error}`)
      })
    }

    const fileName = path.basename(filePath)

    if (fileName === '.ts') {
      // Generated SDK had no name because there was no title in the schema
      // Rename it to the default name
      const directoryPath = path.dirname(filePath)
      const newPath = path.join(directoryPath, `${DEFAULT_SCHEMA_TITLE}.ts`)
      logger.debug(
        `afterAllFilesWriteHandler ~ Renaming ${filePath} to ${newPath}`
      )
      fs.renameSync(filePath, newPath)
    }
  }

  if (emptyFileList.length > 0) {
    logger.debug(
      `afterAllFilesWriteHandler ~ The following files were empty and removed: ${emptyFileList.join(
        ', '
      )}`
    )
  }

  // Return the list of generated file paths excluding the empty files
  const filteredFilePaths = filePaths.filter(
    (filePath) => !emptyFileList.includes(filePath)
  )

  // Check if all the filtered file path end with `.schemas.ts`
  if (filteredFilePaths.every((filePath) => filePath.endsWith('.schemas.ts'))) {
    // If yes we should remove them as only schemas files is not needed
    filteredFilePaths.map(removeSingleFile)
    return []
  }

  return filteredFilePaths
}

export default async ({
  openApiPath,
  outputDir,
  shouldGenerateSampleK6Script,
  analyticsData,
  mode,
  tags,
}: GenerateK6SDKOptions) => {
  /**
   * Note!
   * 1. override.requestOptions is not supported for the custom K6 client
   * 2. override.mutator is not supported for the custom K6 client
   */
  const generatedFilePaths: string[] = []
  await outputOverrider.redirectOutputToNullStream(async () => {
    await orval({
      input: {
        target: openApiPath,
        filters: {
          tags: tags && tags.length > 0 ? tags : undefined,
          // Orval 8 defaults to pruning component schemas that aren't referenced
          // by the tag-filtered operations. Keep all schemas available regardless
          // of tag filtering, matching the previous (orval 7) behavior.
          includeUnreferencedSchemas: true,
        },
        // Orval 8 validates the input schema strictly by default and aborts generation
        // on minor spec issues (e.g. missing `info.title`) that orval 7 tolerated.
        // Keep the previous lenient behavior since this tool's fallback logic
        // (e.g. _setDefaultSchemaTitle) is designed to handle such cases.
        unsafeDisableValidation: true,
      },
      output: {
        target: outputDir,
        mode: mode,
        client: () =>
          getK6ClientBuilder(shouldGenerateSampleK6Script, analyticsData),
        override: {
          header: generatedFileHeaderGenerator,
        },
        headers: true,
      },
      hooks: {
        afterAllFilesWrite: async (...args: unknown[]) => {
          const filePaths = args[0] as string[]
          const filteredFilePaths = await afterAllFilesWriteHandler(
            filePaths,
            outputOverrider
          )
          generatedFilePaths.push(...filteredFilePaths)
        },
      },
    })
  })

  if (generatedFilePaths.length === 0) {
    const tagsMessage =
      tags?.length && tags.length > 0
        ? ` Applied tag filter(s): ${tags.join(', ')}. `
        : ' '
    throw new NoFilesGeneratedError(
      `No files were generated.${tagsMessage}Try running with --verbose flag to get more details.`
    )
  }
}
